//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySunValley {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadySunValley.EmbeddedResource", typeof(EmbeddedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig]
        ///&quot;BypassTPMCheck&quot;=dword:00000001
        ///&quot;BypassSecureBootCheck&quot;=dword:00000001
        ///&quot;BypassRAMCheck&quot;=dword:00000001
        /// ähnelt.
        /// </summary>
        internal static string bypass {
            get {
                return ResourceManager.GetString("bypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3015E
        ///3020E
        ///Athlon Gold 3150C
        ///Athlon Gold 3150U
        ///Athlon Silver 3050C
        ///Athlon Silver 3050e
        ///Athlon Silver 3050U
        ///Athlon 3000G
        ///Athlon 300GE
        ///Athlon 300U
        ///Athlon 320GE
        ///Athlon Gold 3150G
        ///Athlon Gold 3150GE
        ///Athlon Silver 3050GE
        ///EPYC 7232P
        ///EPYC 7252
        ///EPYC 7262
        ///EPYC 7272
        ///EPYC 7282
        ///EPYC 7302
        ///EPYC 7302P
        ///EPYC 7352
        ///EPYC 7402
        ///EPYC 7402P
        ///EPYC 7452
        ///EPYC 7502
        ///EPYC 7502P
        ///EPYC 7532
        ///EPYC 7542
        ///EPYC 7552
        ///EPYC 7642
        ///EPYC 7662
        ///EPYC 7702
        ///EPYC 7702P
        ///EPYC 7742
        ///EPYC 7F32
        ///EPYC 7F52
        ///EPYC 7F72
        ///EPYC 7H12
        ///E [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string supportedCPU {
            get {
                return ResourceManager.GetString("supportedCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Registry Editor Version 5.00
        ///
        ///[-HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig] ähnelt.
        /// </summary>
        internal static string undo_bypass {
            get {
                return ResourceManager.GetString("undo_bypass", resourceCulture);
            }
        }
    }
}
